"use client";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import CssBaseline from "@mui/material/CssBaseline";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Box, Container } from "@mui/material";

// Extend the palette to include greyBackground
declare module "@mui/material/styles" {
  interface Palette {
    greyBackground: Palette["primary"];
  }
  interface PaletteOptions {
    greyBackground?: PaletteOptions["primary"];
  }
}

const theme = createTheme({
  breakpoints: {
    values: {
      xs: 0,
      sm: 600,
      md: 900,
      lg: 1200,
      xl: 1536,
    },
  },
  colorSchemes: {
    light: {
      palette: {
        primary: { main: "#336774" },
        secondary: { main: "#c53d43" },
        warning: { main: "#f8b500" },
        info: { main: "#59b9c6" },
        success: { main: "#028760" },
        greyBackground: { main: "#e5e4e6" },
      },
    },
    dark: {
      palette: {
        primary: { main: "#89c3eb" },
        secondary: { main: "#c53d43" },
        warning: { main: "#f8b500" },
        info: { main: "#59b9c6" },
        success: { main: "#028760" },
        greyBackground: { main: "#524e4d" },
      },
    },
  },
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Box display="flex" flexDirection="column" minHeight="100vh">
              <Header />
              <Container maxWidth="md" sx={{ flex: 1, py: 4 }}>
                {children}
              </Container>
              <Footer />
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
